[ids]
*

[main]
grave = esc
esc = grave
capslock = layer(nav)
# c = timeout(c, 200, semicolon)
ro = ;
; = /
rightalt = ro
/ = rightalt

[nav]
k = up
h = left
j = down
l = right
a = home
d = end
s = pagedown
w = pageup
1 = mute
2 = volumedown
3 = volumeup
4 = playpause
5 = brightnessdown
6 = brightnessup
8 = printscreen
