-- @p lua/colors/_init.lua
-- This section is generated by the theme switcher @p bin/nvim_themes but you can change
-- the colorscheme and the colors by yourself, but notice that if you use the theme switcher
-- it'll overwrite anything in these files, i'll try improving its colors in the future, cuz i did the
-- logic of it, but i was too lazy to search the colors by myself so i asked gemini to do it, and ...,
-- the colors have nothing to do with the colorschemes
local loader = require('utils.loader')

loader.load('colors', {
  'colorscheme',
  -- 'colors',
})
